export const STORAGE_KEYS = {
  TASKS: "atlas-tasks",
  HABITS: "atlas-habits",
  GOALS: "atlas-goals",
  JOURNAL: "atlas-journal",
  SETTINGS: "atlas-settings",
  NOTES: "atlas_notes",
  REMINDERS: "atlas_reminders",
  GYM_WORKOUTS: "atlas_gym_workouts",
  GYM_EXERCISES: "atlas_gym_exercises",
  FOOTBALL_MATCHES: "atlas_football_matches",
  FOOTBALL_TRAINING: "atlas_football_training",
  STUDY_SUBJECTS: "atlas_study_subjects",
  STUDY_SESSIONS: "atlas_study_sessions",
  STUDY_GRADES: "atlas_study_grades",
  PHONE_CONTROL: "atlas_phone_control",
} as const;